export const cates = [
  {
    label: "全部",
    value: "all",
  },
  {
    value: "changdihuizhi",
    label: "场地绘制",
  },
  {
    value: "wufang",
    label: "物防",
  },
  {
    value: "changsuosheshi",
    label: "场所设施",
  },
];

export const columns1 = [
  {
    featureCode: "AREA",
    featureName: "区域",
    featureType: "SITE_DRAWING",
    filePath: "/common/file/feature/QY.png",
    id: 1,
    ueStyle: "",
  },
  {
    featureCode: "ROUTE",
    featureName: "路线",
    featureType: "SITE_DRAWING",
    filePath: "/common/file/feature/LX.png",
    id: 2,
    ueStyle: "",
  },
  {
    featureCode: "SITE_DRAWING",
    featureName: "责任区",
    featureType: "SITE_DRAWING",
    filePath: "/common/file/feature/ZRQ.png",
    id: 3,
    ueStyle: "",
  },
  {
    featureCode: "WALL",
    featureName: "墙",
    featureType: "SITE_DRAWING",
    filePath: "/common/file/feature/Q.png",
    id: 4,
    ueStyle: "",
  },
  {
    featureCode: "BOLLARD",
    featureName: "升降柱",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/SJZ.png",
    id: 5,
    ueStyle: "",
  },
  {
    featureCode: "BOLLARD",
    featureName: "巡逻车",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/XLC.png",
    id: 6,
    ueStyle: "",
  },
  {
    featureCode: "KNIFE_REST",
    featureName: "拒马",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/JM.png",
    id: 7,
    ueStyle: "",
  },
  {
    featureCode: "ANTI_COLLISION",
    featureName: "防冲撞",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/FCZ.png",
    id: 8,
    ueStyle: "",
  },
  {
    featureCode: "GATE",
    featureName: "出入口",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/CRK.png",
    id: 9,
    ueStyle: "",
  },
  {
    featureCode: "SECURITY_GATE",
    featureName: "安检站",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/AJM.png",
    id: 10,
    ueStyle: "",
  },
  {
    featureCode: "FIRE_HYDRANT",
    featureName: "消防栓",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/XFS.png",
    id: 11,
    ueStyle: "",
  },
  {
    featureCode: "GUARDRAIL",
    featureName: "护栏",
    featureType: "PHYSICAL_DEFENSE",
    filePath: "/common/file/feature/HL.png",
    id: 12,
    ueStyle: "",
  },
  {
    featureCode: "PUNCTUATION",
    featureName: "标点",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/BD.png",
    id: 13,
    ueStyle: "",
  },
  {
    featureCode: "TEXT",
    featureName: "文本",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/WB.png",
    id: 14,
    ueStyle: "",
  },
  {
    featureCode: "REST",
    featureName: "休憩",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/XX.png",
    id: 15,
    ueStyle: "",
  },
  {
    featureCode: "TOILET",
    featureName: "公厕",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/GC.png",
    id: 16,
    ueStyle: "",
  },
  {
    featureCode: "PARKING_LOT",
    featureName: "停车场",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/TCC.png",
    id: 17,
    ueStyle: "",
  },
  {
    featureCode: "NO_PARKING",
    featureName: "禁止停车",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/JZTC.png",
    id: 18,
    ueStyle: "",
  },
  {
    featureCode: "POLICE_STATION",
    featureName: "警务站",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/JWZ.png",
    id: 19,
    ueStyle: "",
  },
  {
    featureCode: "STATION",
    featureName: "驿站",
    featureType: "VENUE_FACILITY",
    filePath: "/common/file/feature/YZ.png",
    id: 20,
    ueStyle: "",
  },
];

export const columns = [
  {
    key: "QY",
    cate: "changdihuizhi",
    title: "区域",
    id: 295,
    featureType: "SITE_DRAWING",
    featureName: "gaylord.daniel",
    featureCode: "AREA",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "LX",
    cate: "changdihuizhi",
    title: "路线",
    id: 295,
    featureType: "SITE_DRAWING",
    featureName: "gaylord.daniel",
    featureCode: "ROUTE",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "ZRQ",
    cate: "changdihuizhi",
    title: "责任区",
    id: 295,
    featureType: "SITE_DRAWING",
    featureName: "gaylord.daniel",
    featureCode: "SITE_DRAWING",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "Q",
    cate: "changdihuizhi",
    title: "墙",
    id: 295,
    featureType: "SITE_DRAWING",
    featureName: "gaylord.daniel",
    featureCode: "WALL",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "SJZ",
    cate: "wufang",
    title: "升降柱",

    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "BOLLARD",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "XLC",
    cate: "wufang",
    title: "巡逻车",

    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "BOLLARD",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "JM",
    cate: "wufang",
    title: "拒马",

    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "KNIFE_REST",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "FCZ",
    cate: "wufang",
    title: "防冲撞",

    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "ANTI_COLLISION",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "CRK",
    cate: "wufang",
    title: "出入口",

    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "GATE",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "AJM",
    cate: "wufang",
    title: "安检站",
    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "SECURITY_GATE",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "XFS",
    cate: "wufang",
    title: "消防拴",
    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "FIRE_HYDRANT",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "HL",
    cate: "wufang",
    title: "护栏",

    id: 295,
    featureType: "PHYSICAL_DEFENSE",
    featureName: "gaylord.daniel",
    featureCode: "GUARDRAIL",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "BD",
    cate: "changsuosheshi",
    title: "标点",
    id: 295,
    featureType: "VENUE_FACILITY",
    featureName: "gaylord.daniel",
    featureCode: "PUNCTUATION",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "WB",
    cate: "changsuosheshi",
    title: "文本",
    id: 295,
    featureType: "VENUE_FACILITY",
    featureName: "gaylord.daniel",
    featureCode: "TEXT",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "XX",
    cate: "changsuosheshi",
    title: "休憩",
    id: 295,
    featureType: "VENUE_FACILITY",
    featureName: "gaylord.daniel",
    featureCode: "REST",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "GC",
    cate: "changsuosheshi",
    title: "公厕",
    id: 295,
    featureType: "VENUE_FACILITY",
    featureName: "gaylord.daniel",
    featureCode: "TOILET",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "TCC",
    cate: "changsuosheshi",
    title: "停车场",
    id: 295,
    featureType: "PARKING_LOT",
    featureName: "gaylord.daniel",
    featureCode: "PARKING_LOT",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "JZTC",
    cate: "changsuosheshi",
    title: "禁止停车",

    id: 295,
    featureType: "VENUE_FACILITY",
    featureName: "gaylord.daniel",
    featureCode: "NO_PARKING",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "JWZ",
    cate: "changsuosheshi",
    title: "警务站",
    id: 295,
    featureType: "VENUE_FACILITY",
    featureName: "gaylord.daniel",
    featureCode: "POLICE_STATION",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
  {
    key: "YZ",
    cate: "changsuosheshi",
    title: "驿站",
    id: 295,
    featureType: "sgxhpr",
    featureName: "gaylord.daniel",
    featureCode: "STATION",
    filePath: "t8l1mb",
    ueStyle: "tvknq9",
  },
];

import JX from "@/assets/img/place-manage/icons/JX.png";
import CIRCLE from "@/assets/img/place-manage/icons/CIRCLE.png";
import DBX from "@/assets/img/place-manage/icons/DBX.png";
import QY from "@/assets/img/place-manage/icons/QY.png";
import LX from "@/assets/img/place-manage/icons/LX.png";
import ZRQ from "@/assets/img/place-manage/icons/ZRQ.png";
import Q from "@/assets/img/place-manage/icons/Q.png";
import SJZ from "@/assets/img/place-manage/icons/SJZ.png";
import XLC from "@/assets/img/place-manage/icons/XLC.png";
import JM from "@/assets/img/place-manage/icons/JM.png";
import FCZ from "@/assets/img/place-manage/icons/FCZ.png";
import CRK from "@/assets/img/place-manage/icons/CRK.png";
import AJM from "@/assets/img/place-manage/icons/AJM.png";
import XFS from "@/assets/img/place-manage/icons/XFS.png";
import HL from "@/assets/img/place-manage/icons/HL.png";
import BD from "@/assets/img/place-manage/icons/BD.png";
import WB from "@/assets/img/place-manage/icons/WB.png";
import XX from "@/assets/img/place-manage/icons/XX.png";
import GC from "@/assets/img/place-manage/icons/GC.png";
import TCC from "@/assets/img/place-manage/icons/TCC.png";
import JZTC from "@/assets/img/place-manage/icons/JZTC.png";
import JWZ from "@/assets/img/place-manage/icons/JWZ.png";
import YZ from "@/assets/img/place-manage/icons/YZ.png";

export const icons = {
  JX,
  CIRCLE,
  DBX,
  QY,
  LX,
  ZRQ,
  Q,
  SJZ,
  XLC,
  JM,
  FCZ,
  CRK,
  AJM,
  XFS,
  HL,
  BD,
  WB,
  XX,
  GC,
  TCC,
  JZTC,
  JWZ,
  YZ,
};
